name: Build and push Docker image

on:
  push:
    branches:
      - master

env:
  GH_PAT: ${{ secrets.GH_PAT }}
  IMAGE_NAME: ghcr.io/prefeitura-rio/mlflow-gke


jobs:
  build-container:
    name: Build and publish (Python ${{ matrix.python-version }}, MLflow v${{ matrix.mlflow-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        mlflow-version: [1.28.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and publish image
        run: |
          docker build --build-arg PYTHON_VERSION=${{ matrix.python-version }} --build-arg MLFLOW_VERSION=${{ matrix.mlflow-version }} -t $IMAGE_NAME:$GITHUB_SHA-python${{ matrix.python-version }}-mlflow${{ matrix.mlflow-version }} .
          docker build --build-arg PYTHON_VERSION=${{ matrix.python-version }} --build-arg MLFLOW_VERSION=${{ matrix.mlflow-version }} -t $IMAGE_NAME:latest-python${{ matrix.python-version }}-mlflow${{ matrix.mlflow-version }} .
          echo $GH_PAT | docker login ghcr.io -u gabriel-milan --password-stdin
          docker push $IMAGE_NAME:$GITHUB_SHA-python${{ matrix.python-version }}-mlflow${{ matrix.mlflow-version }}
          docker push $IMAGE_NAME:latest-python${{ matrix.python-version }}-mlflow${{ matrix.mlflow-version }}
